sync:
  defaults:
    symlink:
      mode: "ignore"
    permissions:
      defaultFileMode: 0644
      defaultDirectoryMode: 0775
    mode: two-way-resolved
    ignore:
      paths:
        - "tags"
        - ".idea"
        - ".DS_Store"
        - "*/mysql/databases"
        - "*/node_modules"
      vcs: true
